# Nord
# [colors.primary]
# background = "#2e3440"
# foreground = "#d8dee9"
# dim_foreground = "#a5abb6"
#
# [colors.cursor]
# cursor = "#d8dee9"
# text = "#2e3440"
#
# [colors.search.matches]
# background = "#88c0d0"
# foreground = "CellBackground"
#
# [colors.selection]
# background = "#4c566a"
# text = "CellForeground"
#
# [colors.vi_mode_cursor]
# cursor = "#d8dee9"
# text = "#2e3440"
#
# [colors.search.focused_match]
# foreground = "#2e3440"
# background = "#a3be8c"
#
# [colors.hints.start]
# foreground = "#2e3440"
# background = "#ebcb8b"
#
# [colors.hints.end]
# foreground = "#2e3440"
# background = "#d8dee9"
#
# [colors.footer_bar]
# background = "#2e3440"
# foreground = "#d8dee9"
#
# [colors.normal]
# black = "#3b4252"
# blue = "#81a1c1"
# cyan = "#88c0d0"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#e5e9f0"
# yellow = "#ebcb8b"
#
# [colors.bright]
# black = "#4c566a"
# blue = "#81a1c1"
# cyan = "#8fbcbb"
# green = "#a3be8c"
# magenta = "#b48ead"
# red = "#bf616a"
# white = "#eceff4"
# yellow = "#ebcb8b"
#
# [colors.dim]
# black = "#373e4d"
# blue = "#68809a"
# cyan = "#6d96a5"
# green = "#809575"
# magenta = "#8c738c"
# red = "#94545d"
# white = "#aeb3bb"
# yellow = "#b29e75"

# Github Dark High Contrast
# [colors.primary]
# background = '0x0a0c10'
# foreground = '0xf0f3f6'
# 
# [colors.cursor]
# text = '0x0a0c10'
# cursor = '0xf0f3f6'
# 
# [colors.normal]
# black = '0x7a828e'
# red = '0xff9492'
# green = '0x26cd4d'
# yellow = '0xf0b72f'
# blue = '0x71b7ff'
# magenta = '0xcb9eff'
# cyan = '0x39c5cf'
# white = '0xd9dee3'
# 
# [colors.bright]
# black = '0x9ea7b3'
# red = '0xffb1af'
# green = '0x4ae168'
# yellow = '0xf7c843'
# blue = '0x91cbff'
# magenta = '0xcb9eff'
# cyan = '0x39c5cf'
# white = '0xd9dee3'

 # Colors (Everforest Dark)
 [colors.primary]
 background = '#2d353b'
 foreground = '#d3c6aa'

 [colors.normal]
 black   = '#475258'
 red     = '#e67e80'
 green   = '#a7c080'
 yellow  = '#dbbc7f'
 blue    = '#7fbbb3'
 magenta = '#d699b6'
 cyan    = '#83c092'
 white   = '#d3c6aa'

 [colors.bright]
 black   = '#475258'
 red     = '#e67e80'
 green   = '#a7c080'
 yellow  = '#dbbc7f'
 blue    = '#7fbbb3'
 magenta = '#d699b6'
 cyan    = '#83c092'
 white   = '#d3c6aa'

# Colors (Everforest Light)
# Default colors
# [colors.primary]
# background = '#fdf6e3'
# foreground = '#5c6a72'

# # Normal colors
# [colors.normal]
# black   = '#5c6a72'
# red     = '#f85552'
# green   = '#8da101'
# yellow  = '#dfa000'
# blue    = '#3a94c5'
# magenta = '#df69ba'
# cyan    = '#35a77c'
# white   = '#e0dcc7'

# # Bright Colors
# [colors.bright]
# black   = '#5c6a72'
# red     = '#f85552'
# green   = '#8da101'
# yellow  = '#dfa000'
# blue    = '#3a94c5'
# magenta = '#df69ba'
# cyan    = '#35a77c'
# white   = '#e0dcc7'
 
# Gruvbox Colorscheme
# [colors]
# draw_bold_text_with_bright_colors = true
# 
# [colors.bright]
# black = "0x928374"
# blue = "0x83a598"
# cyan = "0x8ec07c"
# green = "0xb8bb26"
# magenta = "0xd3869b"
# red = "0xfb4934"
# white = "0xebdbb2"
# yellow = "0xfabd2f"
# 
# [colors.normal]
# black = "0x282828"
# blue = "0x458588"
# cyan = "0x689d6a"
# green = "0x98971a"
# magenta = "0xb16286"
# red = "0xcc241d"
# white = "0xa89984"
# yellow = "0xd79921"
# 
# [colors.primary]
# background = "0x282828"
# foreground = "0xebdbb2"

[cursor.style]
blinking = "on"
shape = "Block"

[env]
TERM = "st-256color"
# WINIT_X11_SCALE_FACTOR = "0.75"

[font]
builtin_box_drawing = true
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = true
opacity = 1.0
option_as_alt = "Both"
#option_as_alt = "Both"

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "F11", mods = "None", action = "ToggleFullscreen" }
]
